### ISSUE TITLE
Deploy fellowship site to production

### ISSUE THREAD

**Issue by lossyrob** [azavea/azavea-fellowship-program-site#29]
We'll be launching the fellowship site to `fellowship.azavea.com` on 1/31. This issue will track deployment to production.

@azavea/operations

**Comment by lossyrob** [comment]
@azavea/operations this is good to go. Do you need anything else from us before publish?

**Comment by tnation14** [comment]
Merged `develop` into `master`, site has successfully been deployed.

**Comment by lossyrob** [comment]
:tada:
