### ISSUE TITLE
add Mailchimp list sign up form

### ISSUE THREAD

**Issue by danford1** [azavea/azavea-fellowship-program-site#4]
Full html for Mailchimp form:

[azavea-fellowship-program-mailchimp-list-form.html.zip](https://github.com/azavea/azavea-fellowship-program-site/files/832053/azavea-fellowship-program-mailchimp-list-form.html.zip)

**Comment by danford1** [comment]
@lossyrob note that there are 4 form fields: email, fname, lname, and a checkbox field:

I'm interested in...

- becoming an Azavea Fellow
- helping to promote the program
- sponsoring an Azavea Fellow

We can change any of these fields and generate new code, if necessary.

**Comment by lossyrob** [comment]
Added in f8c18c329ae3ae57d3109ccdb3f49706de286bf4 and 51322d95184248169f26c53222f95c0cd5ce1ff0
